resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/supriyadas13/Project_ToDo.git
      branch: master
    check_every: 1m
  
    - name: todo-image
    type: docker-image
    source:
      repository: <>/todo-services
      insecure_registries: [<>"]
      tag: todo-services
      username: admin
      password: admin

jobs:
  - name: todo-service
    serial: true
    public: true
    plan:
      - get: repo
        trigger: true
      - task: deploy-image
        file: repo/concourse/deploy-image.yml
      - put: todo-service-image
        params:
          file: target/spring-boot-maven-datastore-0.0.1-SNAPSHOT.jar
          name: spring-boot-datastore-0.0.1-SNAPSHOT.jar
          build: repo